runtime: php72

# The below variables are used in the model for the database and cloud bucket
env_variables:
    GOOGLE_STORAGE_BUCKET: cc-gallery-images
    CLOUDSQL_CONNECTION_NAME: cc-assignment-2-275700:australia-southeast1:gallery
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: test123
    CLOUDSQL_DATABASE_NAME: gallery-data
